services:
  ollama-server:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
      - ./startOllama.sh:/startOllama.sh
    entrypoint: ["/bin/bash", "/startOllama.sh"]
    restart: unless-stopped
  web: 
    build: 
      context: .
    stop_signal: SIGINT
    ports: 
      - "8080:8080"
volumes:
  ollama_storage: