services:
  ollama-server:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_HOME=/usr/local/cuda
      - OLLAMA_MAX_LOADED_MODELS=4
      - OLLAMA_KEEP_ALIVE=60
    volumes:
      - ollama_storage:/root/.ollama
      - ./startOllama.sh:/startOllama.sh
    deploy: 
      resources: 
        reservations: 
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: ollama-service
    entrypoint: ["/bin/bash", "/startOllama.sh"]
    restart: unless-stopped
  web: 
    build: 
      context: .
    stop_signal: SIGINT
    ports: 
      - "8080:8080"
volumes:
  ollama_storage: